export VLLM_ATTENTION_BACKEND=XFORMERS

python3 -u -m verl.trainer.main_ppo \
    algorithm.adv_estimator=long2short \   #grpo for reward weighting
    data.train_files=data/deepsacler_selective_token_deduplicated_r_prompt_shuffled/train.parquet \
    data.val_files=data/deepsacler_selective_token_deduplicated_r_prompt_shuffled/test.parquet \
    data.train_batch_size=128 \
    data.val_batch_size=32 \
    data.max_prompt_length=256 \
    data.max_response_length=8192 \
    actor_rollout_ref.model.path=checkpoints/r1-distilled-qwen-1.5b \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.temperature=0.6 \
    actor_rollout_ref.rollout.top_p=0.95 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.project_name='deepscaler_qwen_1.5b_main' \
    trainer.experiment_name='anneal_adaptive_target_token_weight_0.5' \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=10 \
    trainer.test_freq=25 \
    trainer.total_epochs=1 \
    reward_model.reward_manager=group_reward \
    reward_model.use_token=True \
    reward_model.use_adaptive_token=True \
    reward_model.use_anneal_token=True \
    reward_model.use_target_token=True \
    reward_model.token_score_weight=0.5 \
    reward_model.num_steps_per_half_period=100\